#!/bin/bash

# Path to simd binary
SIMD_PATH=~/src/citd/ibc-go-strangelove-private/build/simd

# Source the addresses from the external file
source ./.addresses

# Check number of arguments
if [ "$#" -ne 2 ]; then
    echo "Using default addresses"
    SENDER_COSMOS_ADDRESS=$DEFAULT_SENDER_COSMOS_ADDRESS
    EVM_RECEIVER_ADDRESS=$DEFAULT_EVM_RECEIVER_ADDRESS
else
    # Save arguments to variables
    SENDER_COSMOS_ADDRESS=$1
    EVM_RECEIVER_ADDRESS=$2
fi


# Check if addresses are provided
if [ -z "$SENDER_COSMOS_ADDRESS" ] || [ -z "$EVM_RECEIVER_ADDRESS" ]; then
    echo "Error: both addresses must be provided"
    exit 1
fi

echo "Checking Cosmos address balance: $SENDER_COSMOS_ADDRESS"
"$SIMD_PATH" q bank balance "$SENDER_COSMOS_ADDRESS" stake

echo -e "\nChecking ERC20 address balance in the C-Chain: $EVM_RECEIVER_ADDRESS"
go run app.go balance-erc20 --bc-id C --addr "$EVM_RECEIVER_ADDRESS"