#!/bin/bash

if [[ $# -eq 1 && $1 =~ ^[0-9]+$ ]]; then
  rly tx transfer ibc-1 99999 "${1}stake" 0x976EA74026E726554dB657fA54763abd0C3a0aa9 channel-0 --path demo --debug --memo "memo-test"
else
  rly tx transfer ibc-1 99999 100000000stake 0x976EA74026E726554dB657fA54763abd0C3a0aa9 channel-0 --path demo --debug --memo "memo-test"
fi